// Automatically generated by PASTA
type UUIDFunctionCall = { returnType: "uuid" };
type TimestampFunctionCall = { returnType: "timestamp" };
type JSONValue =
  | string
  | number
  | boolean
  | { [x: string]: JSONValue }
  | Array<JSONValue>;

function uuid() {
  return {
    "type": "call",
    "function": { "name": "gen_random_uuid" },
    "args": [],
    "returnType": "uuid",
  } as UUIDFunctionCall;
}

function now() {
  return (
    {
      "type": "call",
      "function": { "name": "now" },
      "args": [],
      "returnType": "timestamp",
    } as TimestampFunctionCall
  );
}

const functions = {
  now,
  uuid,
};
export type { JSONValue, TimestampFunctionCall };
export { functions, now, uuid };
